In [24]:
import pandas as pd
import numpy as np
import tensorflow as tf

from sklearn.model_selection import train_test_split as tts
from sklearn.preprocessing import StandardScaler,LabelEncoder
from keras.models import Sequential
from keras.layers import Dense,Dropout
print('Imported Successfully')

Imported Successfully

In [25]:
df = pd.read_csv('Datasets\\pokemon_data.csv')
df.head()

,Unnamed: 0,against_water,attack,capture_rate,classfication,defense,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,0,0.5,49,45,Seed Pokémon,49,65,65,45,grass,poison,6.9,1,0
1,1,0.5,62,45,Seed Pokémon,63,80,80,60,grass,poison,13.0,1,0
2,2,0.5,100,45,Seed Pokémon,123,122,120,80,grass,poison,100.0,1,0
3,5,2.0,104,45,Flame Pokémon,78,159,115,100,fire,flying,90.5,1,0
4,11,1.0,45,45,Butterfly Pokémon,50,90,80,70,bug,flying,32.0,1,0

In [26]:
df.drop(['Unnamed: 0'],axis=1)
df.drop(['classfication'],axis=1)
df.drop(['capture_rate'],axis=1)

df.head()

,Unnamed: 0,against_water,attack,capture_rate,classfication,defense,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,0,0.5,49,45,Seed Pokémon,49,65,65,45,grass,poison,6.9,1,0
1,1,0.5,62,45,Seed Pokémon,63,80,80,60,grass,poison,13.0,1,0
2,2,0.5,100,45,Seed Pokémon,123,122,120,80,grass,poison,100.0,1,0
3,5,2.0,104,45,Flame Pokémon,78,159,115,100,fire,flying,90.5,1,0
4,11,1.0,45,45,Butterfly Pokémon,50,90,80,70,bug,flying,32.0,1,0

In [ ]:
for col in ['type1','type2']:
    df[col] = df[col].fillna('unknown')
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

In [28]:
x=  df.drop(columns=['is_legendary'])
y= df['is_legendary']

In [29]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

ValueError: could not convert string to float: '30 (Meteorite)255 (Core)'

In [ ]:
x_train